### ISSUE TITLE
Missing Test Sources

### ISSUE THREAD

**Issue by MkMunich** [AleksaMCode/bnf-parser#1]
Hi,
I'm interested in your project and would like to learn sth about BFN parsing.
I downloaded the source code and tried to open it in MS VisualStudio 2023 and got an error, that sub-project 'test' is missing. Would it be possible to check in the missing source files into github?
Best Regards
Marcel

**Comment by AleksaMCode** [comment]
@MkMunich I'll take a look at the source files and see what is the problem and what file are missing. I'll try to push an update later in the week.
